name: Push Docker Image to ECR

on:
  push:
    branches:
      - main  # Trigger on merge to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Amazon ECR
    - name: Log in to Amazon ECR
      id: login-ecr
      env: 
        AWS_REGION: ${{ secrets.AWS_REGION }}
      uses: aws-actions/amazon-ecr-login@v2
      with:
          aws-region: $AWS_REGION

    # Build, tag, and push the Docker image
    - name: Build, tag, and push Docker image
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        ECR_REPOSITORY_URI: ${{ secrets.ECR_REPOSITORY_URI }}
      run: |
        # Build the Docker image
        docker build -t my-app .

        # Tag the Docker image
        docker tag my-app:latest $ECR_REPOSITORY_URI:latest

        # Push the Docker image to ECR
        docker push $ECR_REPOSITORY_URI:latest
